### ISSUE TITLE
didnt save

### ISSUE THREAD

**Issue by sec13b** [yutianqaq/CSx3Ldr#1]
my steps :
git clone CSx3Ldr.git
└─$ nim -v
Nim Compiler Version 1.6.14 [Linux: amd64]
└─$ nimble -v
nimble v0.13.1 compiled at 2023-06-29 11:09:29
git hash: couldn't determine git hash
 nimble install winim
┌──(kali㉿kali)-[~/Desktop/Client/CSx3Ldr]
└─$ ls -at
 CSx3Ldr.cna  .git  icon.o  img  LICENSE  README.md  ..
                                                                                                                                
┌──(kali㉿kali)-[~/Desktop/Client/CSx3Ldr]
└─$ mkdir /tmp/icon.o

┌──(kali㉿kali)-[~/Desktop/Client/CSx3Ldr]
└─$ cp icon.o /tmp/icon.o

**Comment by yutianqaq** [comment]
```
cd ~/Desktop/Client/CSx3Ldr
rm -rf /tmp/icon.o
cp  icon.o /tmp/icon.o
```
or 

```
cat icon.rc
demo2 ICON "app.ico"

x86_64-w64-mingw32-windres -F pe-x86-64 icon.rc -O coff -o icon.o

cp icon.o /tmp/icon.o
```

**Comment by sec13b** [comment]
x3Ldr.exe (70 kb): 4/26 - kis, mbytes, windef, zonealarm
